"""
Test for year 2024, day 8 solution.
Run tests from project root with `PYTHONPATH=$(pwd) py.test`.
"""

from adventofcode.src.d08 import run


def test_run() -> None:
    test_data = """............
........0...
.....0......
.......0....
....0.......
......A.....
............
............
........A...
.........A..
............
............"""
    assert run(test_data) == (14, 34)
